"""Compatibility façade for path autoencoder experiments."""

from .experiments.autoencoders.path import *  # noqa: F401,F403
from .experiments.autoencoders.path import (
    PathArrayDataset,
    UpsampleConvBlock,
    augment_path,
    augment_pose_training_batch,
    augment_transform_path,
    batch_size_for_step,
    evaluate_path_ae,
    evaluate_pose_path_ae,
    evaluate_structured_transform_ae,
    init_weights,
    learning_rate_for_step,
    load_pose_split,
    load_transform_split,
    path_query,
    pd_read_csv,
    random_batch,
    random_pose_batch,
    random_transform_batch,
    relative_l2,
    rotate_pose_vector,
    rotate_xy,
    transform_bucket_indices,
    weighted_theta_xy,
    write_csv,
)
from .experiments.autoencoders.path import __all__ as _CANONICAL_ALL

__all__ = [
    *_CANONICAL_ALL,
    "PathArrayDataset",
    "UpsampleConvBlock",
    "augment_path",
    "augment_pose_training_batch",
    "augment_transform_path",
    "batch_size_for_step",
    "evaluate_path_ae",
    "evaluate_pose_path_ae",
    "evaluate_structured_transform_ae",
    "init_weights",
    "learning_rate_for_step",
    "load_pose_split",
    "load_transform_split",
    "path_query",
    "pd_read_csv",
    "random_batch",
    "random_pose_batch",
    "random_transform_batch",
    "relative_l2",
    "rotate_pose_vector",
    "rotate_xy",
    "transform_bucket_indices",
    "weighted_theta_xy",
    "write_csv",
]
