"""Compatibility façade for point-set autoencoder experiments."""

from .experiments.autoencoders.point import *  # noqa: F401,F403
from .experiments.autoencoders.point import (
    Phase2ParticleModel,
    ParticleEncoder,
    augment_points,
    budget_defaults,
    cluster_counts,
    cluster_embeddings,
    clustering_metrics,
    dec_target_distribution,
    evaluate_phase2_model,
    fallback_silhouette,
    gmm_labels,
    hdbscan_or_fallback,
    info_nce_loss,
    init_phase2_weights,
    kmeans_labels,
    load_json,
    load_run_summaries,
    make_phase2_plots,
    masked_chamfer_loss,
    move_phase2_batch,
    normalize_array,
    phase2_run_grid,
    random_phase2_batch,
    random_point_mask,
    read_csv_dicts,
    render_phase2_report,
    select_prototypes,
    train_phase2_run,
    write_phase2_embeddings,
)
from .experiments.autoencoders.point import __all__ as _CANONICAL_ALL

__all__ = [
    *_CANONICAL_ALL,
    "Phase2ParticleModel",
    "ParticleEncoder",
    "augment_points",
    "budget_defaults",
    "cluster_counts",
    "cluster_embeddings",
    "clustering_metrics",
    "dec_target_distribution",
    "evaluate_phase2_model",
    "fallback_silhouette",
    "gmm_labels",
    "hdbscan_or_fallback",
    "info_nce_loss",
    "init_phase2_weights",
    "kmeans_labels",
    "load_json",
    "load_run_summaries",
    "make_phase2_plots",
    "masked_chamfer_loss",
    "move_phase2_batch",
    "normalize_array",
    "phase2_run_grid",
    "random_phase2_batch",
    "random_point_mask",
    "read_csv_dicts",
    "render_phase2_report",
    "select_prototypes",
    "train_phase2_run",
    "write_phase2_embeddings",
]
